// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Wi7MahS0V4Vki-VUWVyUAU6mmIlJSGU',
    appId: '1:978135933085:web:5e093b1d2d27258b987474',
    messagingSenderId: '978135933085',
    projectId: 'buddies-gram-9401f',
    authDomain: 'buddies-gram-9401f.firebaseapp.com',
    storageBucket: 'buddies-gram-9401f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA932Y3uwMI9edkZwRSl7pmt0QzHPGHKeI',
    appId: '1:978135933085:android:1199c21d0f2f8665987474',
    messagingSenderId: '978135933085',
    projectId: 'buddies-gram-9401f',
    storageBucket: 'buddies-gram-9401f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLBuC2OTO3Xb0_sy03LqOC-rhyjkIXHEU',
    appId: '1:978135933085:ios:e9858881a0610c5c987474',
    messagingSenderId: '978135933085',
    projectId: 'buddies-gram-9401f',
    storageBucket: 'buddies-gram-9401f.appspot.com',
    androidClientId: '978135933085-9sgmffgqibla3pl3h1j0bkaf8grlt0au.apps.googleusercontent.com',
    iosClientId: '978135933085-rhsf43b2gth3k5cqus5o7pog3ktm9m6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoReverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLBuC2OTO3Xb0_sy03LqOC-rhyjkIXHEU',
    appId: '1:978135933085:ios:66edfaea94902c48987474',
    messagingSenderId: '978135933085',
    projectId: 'buddies-gram-9401f',
    storageBucket: 'buddies-gram-9401f.appspot.com',
    androidClientId: '978135933085-9sgmffgqibla3pl3h1j0bkaf8grlt0au.apps.googleusercontent.com',
    iosClientId: '978135933085-gcik0qq3sdoklnah58s8c7ltrnko6947.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoReverpod.RunnerTests',
  );
}
